package com.wx.nr.dao;

import com.wx.nr.model.NewsKeywords;
import org.springframework.stereotype.Component;

@Component
public interface NewsKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    int insert(NewsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    int insertSelective(NewsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    NewsKeywords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_keywords
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsKeywords record);
}